const crypto=require("node:crypto"),http=require("node:http"),os=require("node:os"),path=require("node:path"),fs=require("node:fs"),QRCode=require("qrcode");
const {WebSocketServer,WebSocket}=require("ws");
const {PROTOCOL_VERSION,chooseAdvertisedHost}=require("./server-config");
const PORT=Number(process.env.PORT||8080),PUBLIC_DIRECTORY=path.join(__dirname,"public"),advertisedHost=chooseAdvertisedHost(os.networkInterfaces(),process.env.GOLFSIM_HOST);
const rooms=new Map(),codes=new Map(),MAX_PLAYERS=4,HOLES_PER_GAME=5;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function makeHoles(){const bands=[[70,105],[105,140],[140,175],[175,215],[215,255]];return bands.sort(()=>Math.random()-.5).map(([a,b],i)=>({number:i+1,yards:crypto.randomInt(a,b+1),lateral:crypto.randomInt(-12,13)}))}
function code(){let c;do c=String(crypto.randomInt(100000,1000000));while(codes.has(c));return c}
function makeRoom(){const r={id:crypto.randomBytes(12).toString("base64url"),token:crypto.randomBytes(24).toString("base64url"),code:code(),controllers:new Map(),displays:new Set(),nextPlayer:1,latest:{},game:{phase:"lobby",holes:[],holeIndex:0,turnIndex:0,turnOrder:[],shots:{},scores:{},winner:null}};rooms.set(r.id,r);codes.set(r.code,r.id);return r}
function publicOrigin(req){return process.env.GOLFSIM_PUBLIC_ORIGIN?.replace(/\/$/,"")||`http://${req.headers.host||`${advertisedHost}:${PORT}`}`}
function pairURL(req,r){return `${publicOrigin(req)}/controller.html?session=${encodeURIComponent(r.id)}&token=${encodeURIComponent(r.token)}`}
function send(s,type,payload){if(s?.readyState===WebSocket.OPEN)s.send(JSON.stringify({protocolVersion:PROTOCOL_VERSION,type,payload}))}
function broadcast(r,type,payload){for(const s of r.displays)send(s,type,payload)}
function leaderboard(r){return [...r.controllers.values()].map(p=>({id:p.id,name:p.name,wins:r.game.scores[p.id]?.wins||0,totalDistance:Math.round((r.game.scores[p.id]?.totalDistance||0)*10)/10})).sort((a,b)=>b.wins-a.wins||a.totalDistance-b.totalDistance)}
function gameState(r){const g=r.game,hole=g.holes[g.holeIndex]||null,turnID=g.turnOrder[g.turnIndex]||null,turnPlayer=r.controllers.get(turnID);return{phase:g.phase,holeNumber:g.phase==="lobby"?0:Math.min(g.holeIndex+1,HOLES_PER_GAME),totalHoles:HOLES_PER_GAME,hole,turnPlayerID:turnID,turnPlayerName:turnPlayer?.name||null,shots:hole?g.shots[hole.number]||[]:[],leaderboard:leaderboard(r),winner:g.winner}}
function roomState(r){return{sessionID:r.id,roomCode:r.code,connected:r.controllers.size>0,maxPlayers:MAX_PLAYERS,players:[...r.controllers.values()].map(p=>({id:p.id,name:p.name,club:p.club||"driver"})),game:gameState(r)}}
const gameClubBases={"driver":245,"3_wood":225,"5_wood":210,"hybrid":195,"4_iron":185,"5_iron":175,"6_iron":165,"7_iron":155,"8_iron":145,"9_iron":132,"pitching_wedge":118,"gap_wedge":105,"sand_wedge":90,"lob_wedge":72,"putter":20};
function gameShot(r){const base=gameClubBases[r.club]||155,rotation=Math.max(0,Number(r.peakRotationalVelocity)||0),acceleration=Math.max(0,Number(r.peakAcceleration)||0),tempo=Number(r.tempoRatio)||3,confidence=clamp(Number(r.confidence)||.5,.25,1),power=clamp(clamp((rotation-.8)/10.5,0,1)*.72+clamp((acceleration-.10)/2.8,0,1)*.28,0,1),tempoScore=clamp(1-Math.abs(tempo-3)/3.2,0,1),orientation=Math.max(0,Number(r.maximumRelativeOrientationChangeDegrees)||0),quality=clamp((tempoScore*.45+clamp((orientation-18)/95,0,1)*.30+confidence*.25)*100,0,100),carry=Math.max(1,Math.round(base*Math.pow(power,1.35)*(.78+.22*quality/100))),seed=Math.sin(orientation*Math.PI/180*2.25),dispersion=(1-quality/100)*10+3,direction=clamp(seed*dispersion*power,-14,14),curve=clamp((seed*dispersion+(3-tempo)*2.5)*power,-25,25);return{carry,lateral:direction+curve}}
function startGame(r){if(!r.controllers.size||r.game.phase!=="lobby")return;r.game={phase:"playing",holes:makeHoles(),holeIndex:0,turnIndex:0,turnOrder:[...r.controllers.keys()],shots:{},scores:{},winner:null};for(const id of r.game.turnOrder)r.game.scores[id]={wins:0,totalDistance:0};broadcast(r,"gameState",gameState(r))}
function finishHole(r){const g=r.game,h=g.holes[g.holeIndex],shots=g.shots[h.number]||[],best=Math.min(...shots.map(s=>s.distance));for(const s of shots.filter(s=>Math.abs(s.distance-best)<.001))g.scores[s.playerID].wins++;if(g.holeIndex>=HOLES_PER_GAME-1){g.phase="complete";g.winner=leaderboard(r)[0]||null}else{g.holeIndex++;g.turnIndex=0}broadcast(r,"gameState",gameState(r))}
function recordShot(r,p,result){const g=r.game;if(g.phase!=="playing"||g.turnOrder[g.turnIndex]!==p.id)return;const h=g.holes[g.holeIndex],shot=gameShot(result),distance=Math.hypot(shot.carry-h.yards,shot.lateral-h.lateral),entry={playerID:p.id,playerName:p.name,carry:shot.carry,lateral:Math.round(shot.lateral*10)/10,distance:Math.round(distance*10)/10};(g.shots[h.number]??=[]).push(entry);g.scores[p.id].totalDistance+=distance;broadcast(r,"shotScored",{...entry,holeNumber:h.number});g.turnIndex++;if(g.turnIndex>=g.turnOrder.length)finishHole(r);else broadcast(r,"gameState",gameState(r))}
function json(res,obj,status=200){res.writeHead(status,{"Content-Type":"application/json","Cache-Control":"no-store"});res.end(JSON.stringify(obj))}
function serveStatic(req,res){const p=req.url==="/"?"/index.html":new URL(req.url,"http://localhost").pathname,f=path.normalize(path.join(PUBLIC_DIRECTORY,p));if(!f.startsWith(PUBLIC_DIRECTORY)){res.writeHead(403).end("Forbidden");return}fs.readFile(f,(e,d)=>{if(e){res.writeHead(404).end("Not found");return}const x=path.extname(f),t={".html":"text/html",".js":"text/javascript",".css":"text/css",".jpg":"image/jpeg",".png":"image/png",".svg":"image/svg+xml"};res.writeHead(200,{"Content-Type":`${t[x]||"application/octet-stream"}; charset=utf-8`,"Cache-Control":"no-store"});res.end(d)})}
const server=http.createServer(async(req,res)=>{res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Methods","GET, OPTIONS");if(req.method==="OPTIONS"){res.writeHead(204).end();return}const u=new URL(req.url,`http://${req.headers.host}`);
if(u.pathname==="/api/session"){const r=makeRoom(),url=pairURL(req,r),qrDataURL=await QRCode.toDataURL(url,{errorCorrectionLevel:"M",margin:2,width:360});json(res,{sessionID:r.id,roomCode:r.code,pairingURL:url,qrDataURL});return}
if(u.pathname==="/api/join"){const id=codes.get((u.searchParams.get("code")||"").replace(/\D/g,"")),r=rooms.get(id);if(!r){json(res,{error:"Room not found"},404);return}if(r.game.phase!=="lobby"){json(res,{error:"Game already started"},409);return}if(r.controllers.size>=MAX_PLAYERS){json(res,{error:"Room is full"},409);return}json(res,{sessionID:r.id,token:r.token,roomCode:r.code,pairingURL:pairURL(req,r)});return}
if(u.pathname==="/api/qr.png"){const r=rooms.get(u.searchParams.get("session"));if(!r){res.writeHead(404).end("Room not found");return}const png=await QRCode.toBuffer(pairURL(req,r),{errorCorrectionLevel:"M",margin:2,width:360,type:"png"});res.writeHead(200,{"Content-Type":"image/png","Cache-Control":"no-store"});res.end(png);return}
if(u.pathname==="/api/state"){const id=u.searchParams.get("session");if(!id){json(res,{ok:true,rooms:rooms.size});return}const r=rooms.get(id);if(!r){json(res,{error:"Room not found"},404);return}json(res,{...roomState(r),...r.latest});return}
serveStatic(req,res)});
const wss=new WebSocketServer({noServer:true});
server.on("upgrade",(req,socket,head)=>{const u=new URL(req.url,`http://${req.headers.host}`),role=u.pathname;if(!["/controller","/display"].includes(role)){socket.destroy();return}const r=rooms.get(u.searchParams.get("session"));if(!r||(role==="/controller"&&u.searchParams.get("token")!==r.token)){socket.write("HTTP/1.1 401 Unauthorized\r
\r
");socket.destroy();return}wss.handleUpgrade(req,socket,head,ws=>wss.emit("connection",ws,req,{role,room:r}))});
wss.on("connection",(socket,req,{role,room:r})=>{socket.isAlive=true;socket.on("pong",()=>socket.isAlive=true);
if(role==="/display"){r.displays.add(socket);send(socket,"displayState",roomState(r));socket.on("message",b=>{let m;try{m=JSON.parse(b.toString())}catch{return}if(m.protocolVersion===PROTOCOL_VERSION&&m.type==="startGame")startGame(r)});socket.on("close",()=>r.displays.delete(socket));return}
if(r.game.phase!=="lobby"||r.controllers.size>=MAX_PLAYERS){send(socket,"roomUnavailable",{message:"Room is full or game already started."});socket.close();return}
const player={id:crypto.randomBytes(6).toString("base64url"),name:`Player ${r.nextPlayer++}`,club:"driver",socket};r.controllers.set(player.id,player);
socket.on("message",b=>{let m;try{m=JSON.parse(b.toString())}catch{return}if(m.protocolVersion!==PROTOCOL_VERSION||!m.type)return;
if(m.type==="phoneHello"){if(m.payload?.playerName?.trim())player.name=m.payload.playerName.trim().slice(0,24);send(socket,"connectionAccepted",{sessionID:r.id,roomCode:r.code,playerID:player.id,playerName:player.name});broadcast(r,"displayState",roomState(r));return}
if(m.type==="ping"){send(socket,"pong",m.payload);return}
if(m.type==="clubSelection")player.club=m.payload.club||player.club;
if(["livePose","clubSelection","swingStatus","swingResult"].includes(m.type)){const payload={...m.payload,playerID:player.id,playerName:player.name};if(m.type==="livePose")r.latest.latestPose=payload;if(m.type==="clubSelection")r.latest.latestClub=payload;if(m.type==="swingStatus")r.latest.latestSwingStatus=payload;if(m.type==="swingResult"){r.latest.latestSwingResult=payload;recordShot(r,player,payload)}broadcast(r,m.type,payload);broadcast(r,"displayState",roomState(r))}});
socket.on("close",()=>{r.controllers.delete(player.id);broadcast(r,"displayState",roomState(r))})});
setInterval(()=>{for(const s of wss.clients){if(!s.isAlive){s.terminate();continue}s.isAlive=false;s.ping()}},15000);
server.listen(PORT,"0.0.0.0",()=>console.log(`thegolfgame realtime server: http://localhost:${PORT}`));
